### ISSUE TITLE
ToDos für ein Programm-Update

### ISSUE THREAD

**Issue by gesi3** [lhoffjann/ManuscriptAssistant#9]
@lhoffjann Es hat sich Änderungsbedarf für das Programm angesammelt. Mittlerweile es ist so viel, dass ich das Programm ohne eine entsprechende Aktualisierung nicht mehr nutzen kann.
Im einzelnen geht es um folgendes:

- [x] XML-Vorlage aktualisieren: https://github.com/lhoffjann/ManuscriptAssistant/issues/7
- [x] facsimile IDs in pb ohne die Endung ".tif": https://github.com/lhoffjann/ManuscriptAssistant/issues/8
- [x] gitlab-Issuevorlage aktualisieren:  https://github.com/lhoffjann/ManuscriptAssistant/issues/6#issuecomment-1600475378
- [x] pdf-Größe mind. halbieren und Ränder entfernen: https://github.com/lhoffjann/ManuscriptAssistant/issues/3

**Comment by lhoffjann** [comment]
@gesi3 Moin! Sollen wir uns dafür am besten einmal zusammensetzen?
